### ISSUE TITLE
Make it work on repos that don't have a github release too

### ISSUE THREAD

**Issue by nikitavoloboev** [TfTHacker/obsidian42-brat#13]
I wanted to install [this plugin](https://github.com/xnhp/obsidian-cursor-blink) using BRAT but was met with 

<img width="353" alt="image" src="https://user-images.githubusercontent.com/6391776/140625743-283fe406-8585-419d-95ad-34a8e7466d1a.png">

I guess the repo has to have a github release (I [opened an issue there](https://github.com/xnhp/obsidian-cursor-blink/issues/2) to create such release).

Still though, it would be nice if no release was found, it would instead `clone` the repo and then tries to read it as release. There will be a main.js file present during the clone so I think we can make it work?

**Comment by claremacrae** [comment]
I would love to see this - thanks for reporting it!

How would it work work repos that have main.ts in version control, but not main.is?

**Comment by nikitavoloboev** [comment]
Both cases should be considered (I don't know if Obsidian accepts main.ts files). 

I am also not sure what happens now if that main.ts was in github release.

**Comment by TfTHacker** [comment]
glad to hear this idea. It is a tough one though. Obsidian requires 2 things, a main.js and manifest.json. The problem with a repository that isn’t packaged into a release is it is very difficult to determine what the plugin author is doing and how to compile his code. In other words, there is no consistency in which to build on.

Also a plugin dev eventually needs to have a manifest.json and release. So I see this as part of the development process and they should learn this early on. In other words, you can’t reliably do a test of something that is already broken (because its not setup). This would defeat the purpose of testing.

What i mean by this is testing isn’t just about testing features, but the build process, the distribution process and so on.

I think the best thing to do is to nudge the dev to do some basic packaging. It is actually easy to learn, about 30 minutes of reading and testing and you are live with a valid beta for BRAT, which means you have a valid plugin to eventually be shipped.

**Comment by claremacrae** [comment]
Sadly I do think this is the right answer.
