### ISSUE TITLE
other option for convenience

### ISSUE THREAD

**Issue by imeed166** [TfTHacker/obsidian42-brat#21]
Could you please add these features to be available in the command palette, if it's easy to implement :
- check for update for non-beta plugin
- update non-beta plugin
- update non-beta theme
- access changelog for beta and non-beta plugin

Thank you very much for everything.

**Comment by TfTHacker** [comment]
Sorry for the long delay in responding. For now, I am not going to take this plugin down that path. Updates can have bugs and users should be aware of what is being updated.  I also think about this from a security standpoint. I don't want to bypass Obsidian's approach to plugins too much.

Having said that, you can add any plugin to BRAT and it will update it.  So instead of registering a plugin through the community plugin browser, do so directly in BRAT and it will auto-update.
