### ISSUE TITLE
Overwrites published plugin

### ISSUE THREAD

**Issue by shabegom** [TfTHacker/obsidian42-brat#24]
Example: Graph Analysis

BRAT will install an older version of a plugin over the newer version available in community plugins. 

Possible solution:
- diff the version number somehow against the published or local version and only update if the beta is newer.

**Comment by TfTHacker** [comment]
Sam, this is a good idea. The problem is the version number is not really a number and its up to dev to determine how they handle this (they can even go backward).

My design approach was when you do a release, you would update the manifest-beta.json to be the same as manifest.json. That way the beta users and testers are all on same version. As you move forward with dev, then you just update the manifest-beta.json.

What do you think of that approach?

**Comment by shabegom** [comment]
That totally works if the dev remembers. I think in this case they did not. I can always file an issue on their repo if there isn't a way for BRAT to check which version between the beta and main manifest is newer.
