### ISSUE TITLE
[Question] Would like to add Minimal 7 as a beta theme

### ISSUE THREAD

**Issue by trainbuffer** [TfTHacker/obsidian42-brat#58]
Hi! Long time BRAT user for beta plugins, but have never tried with a beta theme before now.  

I saw kepano is working on a big re-working of Minimal (https://github.com/kepano/obsidian-minimal/pull/581) and was excited to give it a try as the updates are coming fast. Adding this address `https://github.com/kepano/obsidian-minimal/tree/7` in BRAT under _Add Beta Theme_ shows me the notice:

> There is no theme.css or theme-beta.css in the root path of this repository, so there is no theme to install.

The manifest.json content looks fine, and there's a very recently updated theme.css in there, so I'm not sure what the issue is. Any guidance would be appreciated. Cheers.

Regardless, thanks much for BRAT!

**Comment by TfTHacker** [comment]
I saw Kepano just released the update, nice! I am a minimal theme user as well.

The Beta theme support requires the dev to set up a config file to tell BRAT which beta to use. Otherwise, it won't be able to figure that out independently from a repo. So the them dev would need to add support, which is relatively easy and documented here:
https://tfthacker.com/Obsidian+Plugins+by+TfTHacker/BRAT+-+Beta+Reviewer's+Auto-update+Tool/Working+with+Themes#theme.css%20or%20theme-beta.css

**Comment by TfTHacker** [comment]
Also, thank you for your nice words about BRAT. This is a labor of love :-)

**Comment by trainbuffer** [comment]
I had just heard about the beta ~36hr or so ago, and thought it was going to be a longer process before v7 was released. 😳
Sorry to bother!

**Comment by TfTHacker** [comment]
It was no bother at all. Glad you reached out!
